### PR TITLE
Feature/add forcex86

### PR DESCRIPTION
**Pull request by jburns24**
Was not sure if you typically want to test and bump version number or what tbh this is my first attempt at contributing so I am not sure the 'typical' way things go. I did test this locally and verify it does install the correct version. But given the file guard you have that just checks for `IEDriver.exe` in the correctly versioned directory you must delete this file to get the correct bit version. I am not sure how you would want to address this, for the time being I added it to the README.

### CODE REVIEW

**Comment by dhoer** [comment]
Thanks for your PR 👍 

Since this flag is a new feature, I would bump the minor version to be compliant with http://semver.org. 

The note about removing previous exe is fine.  

The build is hanging due to bundler gem being already installed.  I have pushed a fix for this along with test kitchen, foodcritic and cookstyle fixes.  Can you merge master to this branch?  If the tests pass, then I will merge this PR.

Note that if you would like to adopt this cookbook, I would be more than happy to do that.

**Comment by jburns24** [comment]
Addressing the build failure, but have to run. Will get back to it on Monday.

**Comment by dhoer** [comment]
FYI, to run the rake tests locally try:
```
gem install bundler --no-document
bundle update
rake
```
This should then run the same tests on your local machine.

**Comment by dhoer** [comment]
Added testing readme to master branch.

**Comment by jburns24** [comment]
Thanks for the tip, new to Ruby, had to set up my environment and do some reading but now I am able to locally run rake. Sorry about all the commits trying to figure it out. Before I consulted an associate I was unsure how to test this outside of making another commit.

**Comment by jburns24** [comment]
I attempted to rebase my branch to hide all my indenting commits. looking at commit history that didnt work. If you wanna wait til I figure that out to keep your history cleaner I will try to fix that when I get back from lunch.

**Comment by dhoer** [comment]
Released v2.3.0 to supermarket

**Pull request merged**
